#
#   Joshua Catoe
#   CSCI 473
#   Midterm Exam
#   Makefile - Makefile for joshua_catoe_midterm_ring.c
#

MPICC=mpicc
CFLAGS=-g -Wall -Wstrict-prototypes -std=gnu99

all: joshua_catoe_midterm_ring

joshua_catoe_midterm_ring:
	$(MPICC) $(CFLAGS) -o joshua_catoe_midterm_ring joshua_catoe_midterm_ring.c

clean:
	rm -f joshua_catoe_midterm_ring